### ISSUE TITLE
Traitement des données

### ISSUE THREAD

**Issue by CinquinAndy** [CinquinAndy/tan-dataviz#13]
Traitement et liaisons des données vers Strapi pour avoir toutes les données vers une API que nous gérons nous de notre côté et ne pas avoir les restrictions liées aux API de la tan

**Comment by WadeFade** [comment]
c long j'ai 4Millions de ligne à gérer :')

**Comment by WadeFade** [comment]
c'est sur la bonne voie

**Comment by CinquinAndy** [comment]
> c'est sur la bonne voie

27h27 peut être ?

**Comment by LightInn** [comment]
Franchement les cycles de 24h c'est surfait de fou..

**Comment by WadeFade** [comment]
Mon pc à presque cramé 10fois en voulant nettoyer les données :')

**Comment by WadeFade** [comment]
C fini
j'ai importé toutes les données ! et je suis en train de faire une backup au cas ou
